# should we add hostname to dockerfile

solr:
  image: lukecampbell/docker-ckan-solr
  container_name: solr
  volumes:
    - solr_core_data:/opt/solr/example/solr

postgis:
  image: mdillon/postgis:9.3
  container_name: postgis
  # Override these in a production environment
  environment:
    - POSTGRES_USER=ckanadmin
    - POSTGRES_PASSWORD=ckanadmin
    - POSTGRES_DB=ckan
  volumes:
    - pg_data:/var/lib/postgresql/data

redis:
  image: redis:3.0.7-alpine
  container_name: redis

ioos-catalog:
  build: .
  container_name: docker-ioos-catalog-test
  hostname: catalog-dev.asa.rocks
  links:
    - redis
    - postgis:db
    - solr
  environment:
    - CKAN_INIT=true
    - CKAN_SERVER_NAME=http://catalog-dev.asa.rocks/catalog/
  ports:
    - "80:80"
